name: ACCESS
channels:
  - r
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=anacondar_1
  - bedtools=2.26.0=0
  - binutils_impl_linux-64=2.28.1
  - binutils_linux-64=7.2.0
  - bioconductor-dnacopy=1.58.0
  - bwidget=1.9.11=1
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.14.12
  - curl=7.67.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gcc_impl_linux-64=7.2.0
  - gcc_linux-64=7.2.0
  - gfortran_impl_linux-64=7.2.0
  - gfortran_linux-64=7.2.0
  - glib=2.56.2
  - graphite2=1.3.13
  - gsl=2.4
  - gxx_impl_linux-64=7.2.0
  - gxx_linux-64=7.2.0
  - harfbuzz=1.8.8
  - icu=58.2
  - jpeg=9b
  - krb5=1.16.1
  - libcurl=7.67.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - make=4.2.1
  - ncurses=6.1
  - openssl=1.1.1d
  - pango=1.42.4
  - pcre=8.43
  - pip=19.3.1=py27_0
  - pybedtools=0.7.10
  - pixman=0.38.0
  - python=2.7.17
  - r-ape=5.1
  - r-argparse=1.1.1
  - r-assertthat=0.2.0
  - r-backports=1.1.5
  - r-base=3.5.1
  - r-bh=1.66.0_1
  - r-bibtex=0.4.2
  - r-bindr=0.1.1
  - r-bindrcpp=0.2.2
  - r-bitops=1.0_6
  - r-catools=1.17.1.1
  - r-ckmeans.1d.dp=4.3.0
  - r-cli=1.1.0
  - r-cluster=2.0.7_1
  - r-colorspace=1.3_2
  - r-crayon=1.3.4
  - r-curl=3.2
  - r-data.table=1.11.4
  - r-devtools=1.13.6
  - r-dichromat=2.0_0
  - r-digest=0.6.15
  - r-dplyr=0.8.3
  - r-ellipsis=0.3.0
  - r-fansi=0.4.0
  - r-findpython=1.0.3
  - r-gbrd=0.4_11
  - r-gdata=2.18.0
  - r-getopt=1.20.2
  - r-ggplot2=3.0.0
  - r-git2r=0.23.0
  - r-glue=1.3.0
  - r-gplots=3.0.1
  - r-gridbase=0.4_7
  - r-gridextra=2.3
  - r-gridgraphics=0.4_1
  - r-gtable=0.2.0
  - r-gtools=3.8.1
  - r-httr=1.3.1
  - r-jsonlite=1.5
  - r-kernsmooth=2.23_15
  - r-labeling=0.3
  - r-lattice=0.20_35
  - r-lazyeval=0.2.1
  - r-lifecycle=0.1.0
  - r-magrittr=1.5
  - r-mass=7.3_50
  - r-matrix=1.2_14
  - r-memoise=1.1.0
  - r-memuse=4.0_0
  - r-mgcv=1.8_24
  - r-mime=0.5
  - r-munsell=0.5.0
  - r-nlme=3.1_137
  - r-openssl=1.0.2
  - r-permute=0.9_5
  - r-pillar=1.4.2
  - r-pinfsc50=1.1.0
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-proto=1.0.0
  - r-purrr=0.2.5
  - r-r6=2.2.2
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.3
  - r-rdpack=0.11_0
  - r-reshape2=1.4.3
  - r-rjson=0.2.20
  - r-rlang=0.4.2
  - r-rstudioapi=0.7
  - r-scales=0.5.0
  - r-stringi=1.2.4
  - r-stringr=1.3.1
  - r-tibble=2.1.3
  - r-tidyr=0.8.1
  - r-tidyselect=0.2.5
  - r-utf8=1.1.4
  - r-vcfr=1.8.0
  - r-vctrs=0.2.0
  - r-vegan=2.5_6
  - r-viridislite=0.3.0
  - r-wesanderson=0.3.6
  - r-whisker=0.3_2
  - r-withr=2.1.2
  - r-yaml=2.2.0
  - r-zeallot=0.1.0
  - readline=7.0
  - setuptools=42.0.2=py27_0
  - sqlite=3.30.1
  - tk=8.6.8
  - tktable=2.10
  - wheel=0.33.6=py27_0
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
